config/routes.rb
Rails.application.routes.draw do
  
  devise_for :admins, controllers: { sessions: 'admins/sessions' } 
  devise_for :emails
  devise_for :users, controllers: { sessions: 'users/sessions' }

  resources :reservations do
  resources :restaurants
end
  root to: "reservations#index"

  devise_scope :admin do
	get 'admins/users/list', to: 'admins/sessions#list', as: 'users_list'
end

  get'/restaurantes', to: 'restaurants#index', as: 'restaurants'
end

app/models/reservation.rb
class Reservation < ApplicationRecord
	has_many :restaurants
	belongs_to :user
	
	validates :fecha_registro, presence: true
	validates :cantidad, numericality: {only_integer: true, message: "Solo numeros enteros"}
	validates :fecha_final, presence: true
end

app/controllers/reservations_controller.rb
class ReservationsController < ApplicationController
  before_action :set_reservation, only: [:show, :edit, :update, :destroy]

  # GET /reservations
  # GET /reservations.json
  def index
    @reservations = Reservation.all
  end

  # GET /reservations/1
  # GET /reservations/1.json
  def show
  end

  # GET /reservations/new
  def new
    @reservation = Reservation.new
  end

  # GET /reservations/1/edit
  def edit
  end

  # POST /reservations
  # POST /reservations.json
  def create
    @reservation = Reservation.new(reservation_params)
     @reservation.user_id = current_user.id 

    respond_to do |format|
      if @reservation.save
        format.html { redirect_to @reservation, notice: 'Reservation was successfully created.' }
        format.json { render :show, status: :created, location: @reservation }
      else
        format.html { render :new }
        format.json { render json: @reservation.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /reservations/1
  # PATCH/PUT /reservations/1.json
  def update
    respond_to do |format|
      if @reservation.update(reservation_params)
        format.html { redirect_to @reservation, notice: 'Reservation was successfully updated.' }
        format.json { render :show, status: :ok, location: @reservation }
      else
        format.html { render :edit }
        format.json { render json: @reservation.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /reservations/1
  # DELETE /reservations/1.json
  def destroy
    @reservation.destroy
    respond_to do |format|
      format.html { redirect_to reservations_url, notice: 'Reservation was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_reservation
      @reservation = Reservation.find(params[:id])
    end


    # Never trust parameters from the scary internet, only allow the white list through.
    def reservation_params
      params.require(:reservation).permit(:fecha_registro, :fecha_final, :mounstro, :cantidad, :user_id)
    end
end

app/helpers/reservations_helper.rb
module ReservationsHelper
end

app/views/reservations/_form.html.erb
<%= form_for(reservation) do |f| %>
  <% if reservation.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(reservation.errors.count, "error") %> prohibited this reservation from being saved:</h2>

      <ul>
      <% reservation.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :fecha_registro %>
    <%= f.date_select :fecha_registro %>
  </div>

  <div class="field">
    <%= f.label :fecha_final %>
    <%= f.date_select :fecha_final %>
  </div>

  <div class="field">
    <%= f.label :mounstro %>
    <%= f.text_field :mounstro %>
  </div>

  <div class="field">
    <%= f.label :cantidad %>
    <%= f.number_field :cantidad %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/reservations/edit.html.erb
<h1>Editing Reservation</h1>

<%= render 'form', reservation: @reservation %>

<%= link_to 'Show', @reservation %> |
<%= link_to 'Back', reservations_path %>

app/views/reservations/index.html.erb
<p id="notice"><%= notice %></p>
<% if admin_signed_in? %>
    <% @reservations = Reservation.all %>
    
  <% else %>
   <% @reservations = Reservation.where(user_id: current_user.id) %>
       
  <% end %>
<h1>Reservations</h1>

<table classs="table">
  <thead>
    <tr>
      <th>Fecha registro</th>
      <th>Fecha final</th>
      <th>Mounstro</th>
      <th>Cantidad</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @reservations.each do |reservation| %>
      <tr>
        <td><%= reservation.fecha_registro %></td>
        <td><%= reservation.fecha_final %></td>
        <td><%= reservation.mounstro %></td>
        <td><%= reservation.cantidad %></td>
        <td><%= link_to 'Show', reservation, class: 'button primary tiny' %></td>
        <td><%= link_to 'Edit', edit_reservation_path(reservation),class: 'button warning tiny' %></td>
        <td><%= link_to 'Destroy', reservation, method: :delete, data: { confirm: 'Are you sure?' }, class: 'button alert tiny' %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Reservation', new_reservation_path, class: 'button success tiny'%>

app/views/reservations/new.html.erb
<h1>New Reservation</h1>

<%= render 'form', reservation: @reservation %>

<%= link_to 'Back', reservations_path, class: 'button secondary' %>

app/views/reservations/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Fecha registro:</strong>
  <%= @reservation.fecha_registro %>
</p>

<p>
  <strong>Fecha final:</strong>
  <%= @reservation.fecha_final %>
</p>

<p>
  <strong>Mounstro:</strong>
  <%= @reservation.mounstro %>
</p>

<p>
  <strong>Cantidad:</strong>
  <%= @reservation.cantidad %>
</p>

<table >
<thead>
    <tr>
      <th width=25%>Area</th>
      <th width=25%>Acceso</th>
      <th width=25%>Personas</th>
      <th width=25%>Agregado</th>
      <th colspan="3"></th>
    </tr>   
  </thead>
</table> 
<div id="restaurants">
  <%= render :partial => @reservation.restaurants.reverse %>
</div>

<%= form_for([@reservation, Restaurant.new], remote: true) do |f| %>


<div class="field">
  <%= f.label :Area %>
  <%= f.text_field :area %>
</div>

<div class="field">
  <%= f.label :acceso %>
   <%= f.check_box :acceso %>
</div>

<div class="field">
  <%= f.label :Num_Personas %>
   <%= f.number_field :personas %>
</div>

<div class="actions">
  <%= f.submit "Insertar", class: "button primary" %>
</div>

<% end %>
<%= link_to 'Edit', edit_reservation_path(@reservation), class: "button warning" %> |
<%= link_to 'Back', reservations_path, class: "button secondary" %>