config/routes.rb
Rails.application.routes.draw do
  
  devise_for :admins, controllers: { sessions: 'admins/sessions' } 
  devise_for :emails
  devise_for :users, controllers: { sessions: 'users/sessions' }

  resources :reservations do
  resources :restaurants
end
  root to: "reservations#index"

  devise_scope :admin do
	get 'admins/users/list', to: 'admins/sessions#list', as: 'users_list'
end

  get'/restaurantes', to: 'restaurants#index', as: 'restaurants'
end

app/models/restaurant.rb
class Restaurant < ApplicationRecord
	belongs_to :reservation
	validates :area, presence: true
	validates :acceso, presence: true
	validates :personas, numericality: {only_integer: true, message: "Solo numeros enteros"}
end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController
  before_action :set_restaurant, only: [:show, :edit, :update, :destroy]

  # GET /restaurants
  # GET /restaurants.json
  def index
    @restaurants = Restaurant.all
  end

  # GET /restaurants/1
  # GET /restaurants/1.json
  def show
  end

  # GET /restaurants/new
  def new
    @restaurant = Restaurant.new
  end

  # GET /restaurants/1/edit
  def edit
  end

  # POST /restaurants
  # POST /restaurants.json
  def create
    
    @reservation = Reservation.find(params[:reservation_id])
    @restaurant = @reservation.restaurants.create(restaurant_params)
    
    respond_to do |format|
      if @restaurant.save
        format.html { redirect_to @restaurant, notice: 'Restaurant was successfully created.' }
        format.json { render :show, status: :created, location: @restaurant }
        format.js #create.js.erb
      else
        format.html { render :new }
        format.json { render json: @restaurant.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /restaurants/1
  # PATCH/PUT /restaurants/1.json
  def update
    respond_to do |format|
      if @restaurant.update(restaurant_params)
        format.html { redirect_to @restaurant, notice: 'Restaurant was successfully updated.' }
        format.json { render :show, status: :ok, location: @restaurant }
      else
        format.html { render :edit }
        format.json { render json: @restaurant.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /restaurants/1
  # DELETE /restaurants/1.json
  def destroy
    @restaurant.destroy
    respond_to do |format|
      format.html { redirect_to restaurants_url, notice: 'Restaurant was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_restaurant
      @restaurant = Restaurant.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def restaurant_params
      params.require(:restaurant).permit(:area, :acceso, :personas, :reservation_id)
    end
end

app/helpers/restaurants_helper.rb
module RestaurantsHelper
end

app/views/restaurants/_form.html.erb
<%= form_for(restaurant) do |f| %>
  <% if restaurant.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(restaurant.errors.count, "error") %> prohibited this restaurant from being saved:</h2>

      <ul>
      <% restaurant.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :area %>
    <%= f.text_field :area %>
  </div>

  <div class="field">
    <%= f.label :acceso %>
    <%= f.check_box :acceso %>
  </div>

  <div class="field">
    <%= f.label :personas %>
    <%= f.number_field :personas %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/restaurants/_restaurant.html.erb
<%= div_for restaurant do %>

	<p id="notice"><%= notice %></p>
<table class="table">
  <thead>
  </thead>
  <tbody>
   
      <tr>
        <td width=25%><%= restaurant.area %></td>
        <td width=25%><%= restaurant.acceso ? "Permitido" : "Denegado" %></td>
        <td width=25%><%= restaurant.personas%></td>
       
        <td width=25%><%= time_ago_in_words(restaurant.created_at)%></td>
      </tr>
    
  </tbody>
</table>
<% end %>

app/views/restaurants/create.js.erb
var new_restaurant =$("<%= escape_javascript(render(:partial =>@restaurant))%>").hide();
$('#restaurants').prepend(new_restaurant);
$('#restaurant_<%=@restaurant.id%>').fadeIn('slow');
$('#new_restaurant')[0].reset();

app/views/restaurants/edit.html.erb
<h1>Editing Restaurant</h1>

<%= render 'form', restaurant: @restaurant %>

<%= link_to 'Show', @restaurant %> |
<%= link_to 'Back', restaurants_path %>

app/views/restaurants/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Restaurants</h1>

<table class="table">
  <thead>
    <tr>
      <th>Area</th>
      <th>Acceso</th>
      <th>Personas</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @restaurants.each do |restaurant| %>
      <tr>
        <td><%= restaurant.area %></td>
        <td><%= restaurant.acceso %></td>
        <td><%= restaurant.personas %></td>
        
      </tr>
    <% end %>
  </tbody>
</table>

<br>

app/views/restaurants/new.html.erb
<h1>New Restaurant</h1>

<%= render 'form', restaurant: @restaurant %>

<%= link_to 'Back', restaurants_path %>

app/views/restaurants/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Area:</strong>
  <%= @restaurant.area %>
</p>

<p>
  <strong>Acceso:</strong>
  <%= @restaurant.acceso %>
</p>

<p>
  <strong>Personas:</strong>
  <%= @restaurant.personas %>
</p>

<%= link_to 'Edit', edit_restaurant_path(@restaurant) %> |
<%= link_to 'Back', restaurants_path %>