config/routes.rb
Rails.application.routes.draw do
  
  devise_for :admins, controllers: { sessions: 'admins/sessions' } 
  devise_for :emails
  devise_for :users, controllers: { sessions: 'users/sessions' }

  resources :reservations do
  resources :restaurants
end
  root to: "reservations#index"

  devise_scope :admin do
	get 'admins/users/list', to: 'admins/sessions#list', as: 'users_list'
end

  get'/restaurantes', to: 'restaurants#index', as: 'restaurants'
end

app/views/layouts/_navigation.html.erb
<nav class="navbar navbar-dark bg-primary style="background-color: #e3f2fd;">
  <div class="container">
    <div class="navbar-header">
     <h2> HOTEL TRANSYLVANIA </h2>
    </div>
    <div id="navbar">
  
<ul class="nav navbar-nav pull-left">
      <% if admin_signed_in? %>      
        <li><%= link_to 'Lista de usuarios', users_list_path, class: 'button primary' %></li>
        <li><%= link_to 'Reservaciones', reservations_path, class: 'button primary' %></li>
        <% elsif user_signed_in? %>
        
         <li><%= link_to 'Reservaciones', reservations_path, class: 'button primary' %></li>
         <li><%= link_to 'Restaurantes', '/restaurantes', class: 'button primary' %></li>
       
        <% end %>
      </ul>

    <ul class="nav navbar-nav pull-right">
      <li><% link_to 'Home', reservations_path %></li>
      <ul class="nav navbar-nav pull-right">
      <% if admin_signed_in? %>
      
      <li><%= current_admin.email %></li>
      
        <li><%= link_to 'Editar perfil', edit_admin_registration_path, class: 'button primary' %></li>
        <li><%= link_to 'Log out', destroy_admin_session_path, method: :delete, class: 'button primary' %></li>

        <% elsif user_signed_in? %>
        <li><%= current_user.email %></li>
        <%= image_tag(current_user.avatar_url, :width => 50, :height => 50) if current_user.avatar.present? %>
        
         <li><%= link_to 'Editar perfil', edit_user_registration_path, class: 'button primary' %></li>
        <li><%= link_to 'Log out', destroy_user_session_path, method: :delete, class: 'button primary' %></li>
        <% else %>
          <li><%= link_to 'Log In', new_user_session_path, class: 'button primary' %></li>
          <li><%= link_to 'Sign Up', new_user_registration_path, class: 'button primary' %></li>
        <% end %>
      </ul>
    </ul>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <title><%= content_for?(:title) ? yield(:title) : "Hotel transylvania" %></title>
 
<nav class="indigo">
    <div class="nav-wrapper">
      <a href="#" class="brand-logo center">Hotel Transylvania</a>

      <ul class="left hide-on-med-and-down">
      <% if admin_signed_in? %>      
        <li><%= link_to 'Lista de usuarios', users_list_path, class: 'button primary' %></li>
        <li><%= link_to 'Reservaciones', reservations_path, class: 'button primary' %></li>
        <% elsif user_signed_in? %>
        
         <li><%= link_to 'Reservaciones', reservations_path, class: 'button primary' %></li>
         <li><%= link_to 'Restaurantes', '/restaurantes', class: 'button primary' %></li>
       
        <% end %>
      </ul>


      <ul class="right hide-on-med-and-down">
        <% if admin_signed_in? %> 
    <li> Bienvenido(a) <%= current_admin.email %></li>
    <li><%= link_to 'Editar perfil', edit_admin_registration_path, class: 'button primary' %></li>
    <li><%= link_to 'Cerrar Sesion', destroy_admin_session_path, method: :delete, class: 'button primary' %></li>    
    <% elsif user_signed_in? %>
    <li> Bienvenido(a) <%= current_user.email %></li>
    <%= image_tag(current_user.avatar_url, :width => 50, :height => 50) if current_user.avatar.present? %>

    <li><%= link_to 'Editar perfil', edit_user_registration_path, class: 'button primary' %></li>
    <li><%= link_to 'Cerrar Sesion', destroy_user_session_path, method: :delete, class: 'button primary' %></li>
    <% else %>
      <li><%= link_to 'Entrar',  new_user_session_path, class: 'button primary' %></li>
      <li><%= link_to 'Registrarse',  new_user_registration_path, class: 'button primary' %></li>
    <% end %>
      </ul>
      
    </div>
  
  </nav>

    <div id="flash">
      <% flash.each do |key, value| %>
        <div class="flash <%= key %>"><%= value %></div>
      <% end %>
    </div>
    
  

    <%= stylesheet_link_tag    "application" %>
    <%= javascript_include_tag "application", 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
  </head>

  <body>
    
    <%= yield %>
    
  </body>
</html>